### ISSUE TITLE
Report to Murillo

### ISSUE THREAD

**Issue by primoitt83** [medooze/sdp#1]
Heya Murillo!!

Late in the night but I'm still here!! :D

Tested on my new system:
SO: Ubuntu 16.04.2 LTS
Java: Oracle JDK 1.7 (not OpenJDK) build 1.7.0_80-b15

I've tryed your brand new source and the build was successfull

The console has showed me some warnings but it compiled a sdp.jar file in the folder /dist.

I dont' know if its worth or not but the messages I said are below:

# ant -Dplatforms.JDK_1.7.home=$JAVA_HOME

Buildfile: /usr/local/src/sdp/build.xml

-pre-init:

-init-private:

-init-user:

-init-project:

-init-macrodef-property:

-do-init:

-post-init:

-init-check:

-init-ap-cmdline-properties:

-init-macrodef-javac-with-processors:

-init-macrodef-javac-without-processors:

-init-macrodef-javac:

-init-macrodef-test-impl:

-init-macrodef-junit-init:

-init-macrodef-junit-single:

-init-test-properties:

-init-macrodef-junit-batch:

-init-macrodef-junit:

-init-macrodef-junit-impl:

Trying to override old definition of task http://www.netbeans.org/ns/j2se-projec                                                                                        t/3:test-impl

-init-macrodef-testng:

-init-macrodef-testng-impl:

-init-macrodef-test:

-init-macrodef-junit-debug:

-init-macrodef-junit-debug-batch:

-init-macrodef-junit-debug-impl:

-init-macrodef-test-debug-junit:

-init-macrodef-testng-debug:

-init-macrodef-testng-debug-impl:

-init-macrodef-test-debug-testng:

-init-macrodef-test-debug:

-init-debug-args:

-init-macrodef-nbjpda:

-init-macrodef-debug:

-init-macrodef-java:

-init-presetdef-jar:

-init-ap-cmdline-supported:

-init-ap-cmdline:

init:

-deps-jar-init:

deps-jar:

-check-automatic-build:

-clean-after-automatic-build:

-verify-automatic-build:

-pre-pre-compile:

    [mkdir] Created dir: /usr/local/src/sdp/build/classes

-pre-compile:

-copy-persistence-xml:

-compile-depend:

-do-compile:

    [mkdir] Created dir: /usr/local/src/sdp/build/empty

    [mkdir] Created dir: /usr/local/src/sdp/build/generated-sources/ap-source-ou                                                                                        tput

    [javac] Compiling 275 source files to /usr/local/src/sdp/build/classes

    [javac] warning: [options] bootstrap class path not set in conjunction with                                                                                         -source 1.6

    [javac] 1 warning

    [copy] Copying 1 file to /usr/local/src/sdp/build/classes

-post-compile:

compile:

-pre-pre-compile-test:

-pre-compile-test:

-compile-test-depend:

-do-compile-test:

-post-compile-test:

compile-test:

-pre-test-run:

-do-test-run:

test-report:

-post-test-run:

-test-browse:

test:

-pre-jar:

-pre-pre-jar:

    [mkdir] Created dir: /usr/local/src/sdp/dist

-do-jar-create-manifest:

-do-jar-copy-manifest:

-do-jar-set-mainclass:

-do-jar-set-profile:

-do-jar-set-splashscreen:

-do-jar-jar:

[j2seproject1:jar] Building jar: /usr/local/src/sdp/dist/sdp.jar

    [echo] To run this application from the command line without Ant, try:

    [echo] /usr/lib/jvm/java-7-oracle/bin/java -cp /usr/local/src/sdp/dist/sdp.                                                                                        jar org.murillo.abnf.Parser

-init-macrodef-copylibs:

-do-jar-copylibs:

-do-jar-delete-manifest:

-do-jar-without-libraries:

-do-jar-with-libraries:

-post-jar:

-do-jar:

jar:

-javadoc-build:

 [javadoc] Generating Javadoc

 [javadoc] Javadoc execution

 [javadoc] warning: [options] bootstrap class path not set in conjunction with                                                                                         -source 1.6

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/Attribute                                                                                        .java...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/Bandwidth                                                                                        .java...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/Bandwitdh                                                                                        .java...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/BaseAttri                                                                                        bute.java...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/CNameAttr                                                                                        ibute.java...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/Candidate                                                                                        Attribute.java...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/Connectio                                                                                        n.java...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/CryptoAtt                                                                                        ribute.java...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/ExtMapAtt                                                                                        ribute.java...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/Fingerpri                                                                                        ntAttribute.java...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/FormatAtt                                                                                        ribute.java...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/GroupAttr                                                                                        ibute.java...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/Informati                                                                                        on.java...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/Key.java.                                                                                        ..

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/MediaDesc                                                                                        ription.java...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/MidAttrib                                                                                        ute.java...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/Origin.ja                                                                                        va...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/ParserExc                                                                                        eption.java...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/PreviousS                                                                                        SRCAttribute.java...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/RTPMapAtt                                                                                        ribute.java...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/SCTPMapAt                                                                                        tribute.java...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/SSRCAttri                                                                                        bute.java...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/SSRCGroup                                                                                        Attribute.java...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/SessionDe                                                                                        scription.java...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/SessionNa                                                                                        me.java...

 [javadoc] Loading source file /usr/local/src/sdp/src/org/murillo/sdp/Time.java                                                                                        ...

 [javadoc] Constructing Javadoc information...

 [javadoc] /usr/local/src/sdp/src/org/murillo/sdp/ParserException.java:14: erro                                                                                        r: package org.murillo.abnf does not exist

 [javadoc] public class ParserException extends org.murillo.abnf.ParserExceptio                                                                                        n {

 [javadoc]                                                      ^

 [javadoc] /usr/local/src/sdp/src/org/murillo/sdp/SessionDescription.java:12: e                                                                                        rror: package org.murillo.abnf does not exist

 [javadoc] import org.murillo.abnf.ParserContext;

 [javadoc]                        ^

 [javadoc] /usr/local/src/sdp/src/org/murillo/sdp/SessionDescription.java:13: e                                                                                        rror: package org.murillo.abnf does not exist

 [javadoc] import org.murillo.abnf.Rule$session_description;

 [javadoc]                        ^

 [javadoc] /usr/local/src/sdp/src/org/murillo/sdp/SessionDescription.java:14: e                                                                                        rror: package org.murillo.sdp.impl does not exist

 [javadoc] import org.murillo.sdp.impl.SessionDescriptionBuilder;

 [javadoc]                            ^

 [javadoc] Standard Doclet version 1.7.0_80

 [javadoc] Building tree for all the packages and classes...

 [javadoc] Building index for all the packages and classes...

 [javadoc] Building index for all classes...

 [javadoc] Generating /usr/local/src/sdp/docs/help-doc.html...

 [javadoc] 5 warnings

-javadoc-browse:

javadoc:

default:

BUILD SUCCESSFUL
Total time: 44 seconds

**Comment by murillo128** [comment]
The warnings are only on the javadoc phase, they are harmless

**Comment by murillo128** [comment]
Thanxs for reporting anyway!

**Comment by primoitt83** [comment]
Np!! It's good to hear that!! Now I gonna try compiling media mixer on my new system. Thx!!
